version: '2'

services:
  web:
    build: .
    command: bundle exec shotgun --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - db

  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres-db-volume:/data/postgres
    environment:
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres-db-volume:
